version: "3.7"

services:
    # backend api
    smart-brain-api:
        container_name: backend-api
        # image: node:12.16.1
        build: ./
        working_dir: /usr/src/smart-brain-api
        command: npm run start:dev
        environment: 
            POSTGRES_URI: postgres://andronikus:secret@postgres:5432/smart-brain-docker
            REDIS_URI: redis://redis:6379
        links: 
            - postgres
            - redis
        ports: 
            - "3001:3001"
        volumes: 
            - ./:/usr/src/smart-brain-api
     
    # to use with nginx to simulate a load balance
    #smart-brain-api02:
    #    container_name: backend-api2
    #    # image: node:12.16.1
    #    build: ./
    #    working_dir: /usr/src/smart-brain-api
    #    command: npm run start:dev
    #    environment: 
    #        POSTGRES_URI: postgres://andronikus:secret@postgres:5432/smart-brain-docker
    #        REDIS_URI: redis://redis:6379
    #        PORT: 3002
    #    links: 
    #        - postgres
    #        - redis
    #    ports: 
    #        - "3002:3002"
    #    volumes: 
    #        - ./:/usr/src/smart-brain-api
            
    # database
    postgres:
        container_name: postgres-db
        build: ./postgres
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: andronikus
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
    # redis
    redis:
        image: redis
        ports: 
            - "6379:6379"
    #nginx 
    #load-balancer:
    #    build: nginx/
    #    ports: 
    #        - 80:80
    #    links: 
    #        - smart-brain-api
    #        - smart-brain-api02
