version: "3.7"

services:
    # backend api
    smart-brain-api:
        container_name: backend-api
        # image: node:12.16.1
        build: ./
        working_dir: /usr/src/smart-brain-api
        command: npm run start:dev
        environment: 
            POSTGRES_URI: postgres://andronikus:secret@smart-brain-database:5432/smart-brain-docker
            REDIS_URI: redis://redis:6379
        links: 
            - postgres
            - redis
        ports: 
            - "3001:3001"
        volumes: 
            - ./:/usr/src/smart-brain-api
    
    # database
    postgres:
        container_name: postgres-db
        build: ./postgres
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: andronikus
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: smart-brain-database
    # redis
    redis:
        image: redis
        ports: 
            - "6379:6379"


