version: "3.7"

services:
    smart-brain-api:
        container_name: backend
        # image: node:12.16.1
        build: ./
        working_dir: /usr/src/smart-brain-api
        command: npm run start:dev
        ports: 
            - "3001:3001"
        volumes: 
            - ./:/usr/src/smart-brain-api